# Automatically run checks over changed files prior to `git commit`.
# Required one-time setup:
#
#   pip install pre-commit
#   pre-commit install
#
# See https://pre-commit.com for details.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format