name: Run Sigstore Signer tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  test-sigstore:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'secure-systems-lab' # only run upstream

    permissions:
      id-token: 'write' # ambient credential is used to sign

    steps:
      - name: Checkout securesystemslib
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - name: Set up Python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade tox

      - run: |
          export CERT_ID=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/.github/workflows/test-sigstore.yml@${GITHUB_REF}
          export CERT_ISSUER=https://token.actions.githubusercontent.com
          tox -e sigstore

      - name: File an issue on failure
        if: ${{ failure() }}
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        with:
          script: |
              const repo = context.repo.owner + "/" + context.repo.repo
              const issues = await github.rest.search.issuesAndPullRequests({
                q: "Sigstore+tests+failed+in:title+state:open+type:issue+repo:" + repo,
              })
              if (issues.data.total_count > 0) {
                console.log("Issue open already, not creating.")
              } else {
                await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: "Sigstore tests failed",
                  body: "Hey, it seems Sigstore tests have failed, please see - [workflow run](" +
                        "https://github.com/" + repo + "/actions/runs/" + context.runId + ")"
                })
                console.log("New issue created.")
              }
